name: Build LaTeX documents

on: [push]

jobs:

  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX documents
        uses: dante-ev/latex-action@master
        with:
          root_file: |
            resume.tex
            resume_fr.tex

      - name: Create folder and move files
        run: |
            mkdir /home/runner/work/resume/resume/artifacts
            cp /home/runner/work/resume/resume/resume.pdf /home/runner/work/resume/resume/artifacts/resume.pdf
            cp /home/runner/work/resume/resume/resume_fr.pdf /home/runner/work/resume/resume/artifacts/resume_fr.pdf

      - name: Upload PDF files to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: /home/runner/work/resume/resume/artifacts
